version: 2

build:
  os: ubuntu-24.04 
  tools:
    python: "3.14" 

commands:
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - $HOME/.cargo/bin/uv sync --all-extras --dev
  - $HOME/.cargo/bin/uv run zensical build --site-dir _build/html

formats: []
python:
  install:
    - method: pip
      path: .
