version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.14" 
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - $HOME/.local/bin/uv sync --all-extras --dev --no-install-project
    - $HOME/.local/bin/uv run zensical build -d $READTHEDOCS_OUTPUT/html
