version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.14"
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - $HOME/.cargo/bin/uv sync --all-extras --dev --no-install-project
    - $HOME/.cargo/bin/uv run zensical build --site-dir $READTHEDOCS_OUTPUT/html
